import React,{useMemo,useState} from 'react';
import {BookOpen,Brain,Check,Code2,GitCompare,Lock,Network,Search,Shield,Sparkles,Target,Wrench} from 'lucide-react';
import {lexiconData} from '../data/lexiconData';
import {extendedLexiconData} from '../data/extendedLexiconData';
import {toolsData} from '../data/toolsData';
import {promptsData} from '../data/promptsData';
import {learningPaths,localStack,modelProfiles} from '../data/aiHubData';
import {localAIEntries,localAIPlatforms,localAIQuickStart} from '../data/localAiData';

type Section='overview'|'tools'|'compare'|'decision'|'prompts'|'learn'|'agents'|'local'|'trust';
const sections:[Section,string,any][]=[['overview','AI Hub',Brain],['tools','Tool Explorer',Wrench],['compare','Model-Vergleich',GitCompare],['decision','Entscheidungsassistent',Target],['prompts','Prompt Lab',Sparkles],['learn','Lernpfade',BookOpen],['agents','Agent Architecture',Network],['local','Local AI',Code2],['trust','Trust & Quality',Shield]];
const allLexicon=[...lexiconData,...extendedLexiconData];
const AIHub:React.FC=()=>{const [section,setSection]=useState<Section>('overview');const [query,setQuery]=useState('');const [freeOnly,setFreeOnly]=useState(false);const [localOnly,setLocalOnly]=useState(false);const [goal,setGoal]=useState('');const [privacy,setPrivacy]=useState('egal');const [prompt,setPrompt]=useState('');const [optimized,setOptimized]=useState('');
const search=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return allLexicon.slice(0,12);return allLexicon.filter(x=>(x.term+' '+x.definition+' '+x.category).toLowerCase().includes(q)).slice(0,20)},[query]);
const toolResults=useMemo(()=>{const q=query.trim().toLowerCase();return toolsData.filter(t=>(!q||(t.name+' '+t.description+' '+t.features.join(' ')+' '+t.tags.join(' ')).toLowerCase().includes(q))&&(!freeOnly||!t.isPremium)&&(!localOnly||t.tags.some(x=>/local|open|offline|self/i.test(x)))).slice(0,18)},[query,freeOnly,localOnly]);
const recommendations=useMemo(()=>{if(!goal)return toolsData.slice(0,5);const q=(goal+' '+privacy).toLowerCase();return [...toolsData].sort((a,b)=>score(b,q)-score(a,q)).slice(0,5)},[goal,privacy]);
function score(t:any,q:string){let s=t.rating*2;s+=t.tags.filter((x:string)=>q.includes(x.toLowerCase())).length*2;if(q.includes('kostenlos')&&!t.isPremium)s+=3;if(q.includes('privacy')&&t.tags.some((x:string)=>/local|privacy|offline/i.test(x)))s+=4;return s}
function optimize(){const base=prompt.trim();if(!base){setOptimized('Bitte zuerst einen Prompt eingeben.');return}setOptimized('Rolle: Expertin/Experte für die Aufgabe.\nZiel: '+base+'\nKontext: [relevante Daten ergänzen]\nAnforderungen: klare, überprüfbare Antwort; Unsicherheiten kennzeichnen; Annahmen offenlegen.\nAusgabeformat: strukturierte Schritte + Ergebnis + kurze Qualitätskontrolle.');}
return <div className="min-h-screen bg-slate-50"><div className="max-w-7xl mx-auto px-4 py-8"><div className="mb-8"><p className="text-sm font-semibold text-blue-600">FREE-AI 2.0</p><h1 className="text-4xl font-black text-slate-900">AI Knowledge & Discovery Hub</h1><p className="text-slate-600 mt-2 max-w-3xl">Lexikon, Toolsuche, Modellvergleich, Entscheidungslogik, Prompt Engineering, Lernpfade, Agentenarchitektur, Local AI und Qualitätskontrolle in einer Oberfläche.</p></div>
<div className="flex gap-2 overflow-x-auto pb-3">{sections.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`flex items-center gap-2 px-4 py-2 rounded-xl whitespace-nowrap ${section===id?'bg-slate-900 text-white':'bg-white text-slate-600 border'}`}><Icon size={16}/>{label}</button>)}</div>
{section==='overview'&&<div className="grid md:grid-cols-3 gap-5 mt-6">{[['Lexikon',allLexicon.length+' Begriffe',BookOpen],['Tools',toolsData.length+' Einträge',Wrench],['Prompts',promptsData.length+' Vorlagen',Sparkles],['Modelle',modelProfiles.length+' Profile',GitCompare],['Lernpfade',learningPaths.length+' Pfade',BookOpen],['Local AI',localStack.length+' Bausteine',Lock]].map(([a,b,I])=><button onClick={()=>setSection(a==='Lexikon'?'overview':a==='Modelle'?'compare':a==='Lernpfade'?'learn':a==='Local AI'?'local':'overview')} key={String(a)} className="text-left bg-white rounded-2xl p-6 shadow-sm border hover:shadow-md"><I className="text-blue-600 mb-4"/><div className="font-bold text-xl">{a}</div><div className="text-slate-500">{b}</div></button>)}</div>}
{section==='tools'&&<div className="mt-6"><div className="flex gap-3 mb-5"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tool oder Anwendungsfall suchen..." className="flex-1 rounded-xl border px-4 py-3"/><label className="bg-white border rounded-xl px-4 py-3"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/> kostenlos</label><label className="bg-white border rounded-xl px-4 py-3"><input type="checkbox" checked={localOnly} onChange={e=>setLocalOnly(e.target.checked)}/> lokal/open</label></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{toolResults.map(t=><a key={t.id} href={t.url} target="_blank" rel="noreferrer" className="bg-white rounded-2xl border p-5 hover:shadow-md"><div className="flex justify-between"><b>{t.name}</b><span>★ {t.rating.toFixed(1)}</span></div><p className="text-sm text-slate-600 mt-2">{t.description}</p><div className="flex flex-wrap gap-1 mt-3">{t.tags.slice(0,4).map(x=><span key={x} className="text-xs bg-slate-100 px-2 py-1 rounded">{x}</span>)}</div></a>)}</div></div>}
{section==='compare'&&<div className="mt-6 bg-white rounded-2xl border overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b">{['Modell','Stärken','Local','API','Datenschutz','Preis'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{modelProfiles.map(m=><tr className="border-b last:border-0" key={m.name}><td className="p-4 font-bold">{m.name}<div className="text-xs text-slate-400">{m.family}</div></td><td className="p-4">{m.strengths.join(', ')}</td><td className="p-4">{m.local?'✓':'—'}</td><td className="p-4">{m.api?'✓':'—'}</td><td className="p-4">{m.privacy}</td><td className="p-4">{m.pricing}</td></tr>)}</tbody></table></div>}
{section==='decision'&&<div className="mt-6 grid lg:grid-cols-2 gap-6"><div className="bg-white rounded-2xl border p-6"><h2 className="text-xl font-bold">Was willst du erreichen?</h2><textarea value={goal} onChange={e=>setGoal(e.target.value)} className="w-full border rounded-xl p-4 mt-4 h-32" placeholder="z. B. kostenlose KI für Videoschnitt ohne Anmeldung"/><select value={privacy} onChange={e=>setPrivacy(e.target.value)} className="w-full border rounded-xl p-3 mt-3"><option value="egal">Datenschutz egal</option><option value="privacy">Datenschutz / lokal wichtig</option><option value="kostenlos">Kostenlos wichtig</option></select></div><div><h2 className="font-bold mb-3">Top-Empfehlungen</h2>{recommendations.map(t=><div key={t.id} className="bg-white border rounded-xl p-4 mb-3"><b>{t.name}</b><p className="text-sm text-slate-600">{t.description}</p><div className="text-xs text-blue-600 mt-2">Score {score(t,(goal+' '+privacy).toLowerCase()).toFixed(1)}</div></div>)}</div></div>}
{section==='prompts'&&<div className="mt-6 grid lg:grid-cols-2 gap-6"><div className="bg-white border rounded-2xl p-6"><h2 className="font-bold text-xl">Prompt Optimizer</h2><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} className="w-full border rounded-xl p-4 mt-4 h-48" placeholder="Schreibe deinen Roh-Prompt..."/><button onClick={optimize} className="mt-3 bg-slate-900 text-white px-5 py-3 rounded-xl">Optimieren</button></div><div className="bg-white border rounded-2xl p-6"><h2 className="font-bold text-xl">Strukturierter Prompt</h2><pre className="whitespace-pre-wrap text-sm text-slate-700 mt-4">{optimized||'Hier erscheint die optimierte Version.'}</pre></div></div>}
{section==='learn'&&<div className="grid md:grid-cols-2 gap-5 mt-6">{learningPaths.map(p=><div key={p.name} className="bg-white border rounded-2xl p-6"><div className="text-xs text-blue-600 font-semibold">{p.level}</div><h2 className="text-xl font-bold mt-1">{p.name}</h2><ol className="mt-4 space-y-2">{p.steps.map((s,i)=><li key={s} className="flex gap-3"><span className="w-6 h-6 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center text-xs">{i+1}</span>{s}</li>)}</ol></div>)}</div>}
{section==='agents'&&<div className="mt-6 bg-white border rounded-2xl p-6"><h2 className="text-2xl font-bold">Agent Architecture</h2><div className="grid md:grid-cols-5 gap-3 mt-6">{[['1','Intent',Target],['2','Plan',Brain],['3','Retrieve',Search],['4','Tools / MCP',Wrench],['5','Evaluate',Shield]].map(([n,t,I])=><div key={String(n)} className="p-5 rounded-xl bg-slate-50 border"><I className="text-blue-600"/><div className="font-bold mt-3">{n}. {t}</div></div>)}</div><p className="mt-6 text-slate-600">Sicheres Muster: minimale Tool-Rechte, strukturierte Outputs, Logging, Evaluation und menschliche Freigabe bei kritischen Aktionen.</p></div>}
{section==='local'&&<div className="mt-6 space-y-8"><div className="bg-white border rounded-2xl p-6"><h2 className="text-2xl font-bold">Lokale KI: von 0 bis zum eigenen KI-Server</h2><p className="text-slate-600 mt-2">Nicht jedes Gerät kann jedes Modell ausführen. Entscheidend sind Hardware, Modellgröße, Quantisierung, Runtime und Lizenz.</p><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-3 mt-5">{localAIQuickStart.map(x=><div key={x.step} className="bg-slate-50 border rounded-xl p-4"><div className="text-xs text-blue-600 font-bold">Schritt {x.step}</div><b>{x.title}</b><p className="text-sm text-slate-600 mt-1">{x.detail}</p></div>)}</div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{localAIEntries.map(x=><div key={x.id} className="bg-white border rounded-2xl p-6"><div className="flex justify-between gap-3"><span className="text-xs text-blue-600 font-semibold">{x.category}</span><span className="text-xs">{x.free?'kostenlos':'Kosten beachten'}</span></div><h3 className="font-bold text-xl mt-2">{x.title}</h3><p className="text-slate-600 mt-2">{x.summary}</p><div className="text-xs text-slate-500 mt-3">Plattformen: {x.platforms.join(', ')}</div><ul className="text-sm text-slate-600 mt-3 list-disc pl-5">{x.notes.slice(0,2).map(n=><li key={n}>{n}</li>)}</ul>{x.officialUrl&&<a href={x.officialUrl} target="_blank" rel="noreferrer" className="inline-block mt-4 text-sm text-blue-600">Offizielle Seite →</a>}</div>)}</div><div className="bg-white border rounded-2xl p-6"><h2 className="text-xl font-bold">Geräte und Plattformen</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">{localAIPlatforms.map(p=><div key={p.name} className="border rounded-xl p-4"><b>{p.name}</b><div className="text-xs text-blue-600 mt-1">{p.level}</div><p className="text-sm text-slate-600 mt-2">{p.bestFor}</p></div>)}</div></div></div>}
{section==='trust'&&<div className="mt-6 grid md:grid-cols-2 gap-5">{[['Datenherkunft','Jeder Datensatz sollte Quelle, Status und Prüfdaten erhalten.'],['Modellvergleich','Preis, Limits und Fähigkeiten ändern sich; daher keine zeitlosen Behauptungen.'],['Tool-Qualität','Empfehlungen werden nach Aufgabe, Kosten, Plattform, API und Datenschutz bewertet.'],['Sicherheit','Agenten benötigen Least Privilege, Sandboxing, Prompt-Injection-Schutz und Human Oversight.'],['Evaluation','Golden Datasets, Regressionstests und Human Evaluation verhindern stille Qualitätsverluste.'],['Transparenz','Unsicherheiten und fehlende Verifikation werden sichtbar statt als Fakten ausgegeben.']].map(([a,b])=><div key={a} className="bg-white border rounded-2xl p-6"><Check className="text-green-600"/><h2 className="font-bold mt-3">{a}</h2><p className="text-slate-600 mt-2">{b}</p></div>)}</div>}
{(section==='overview'||section==='tools')&&<div className="mt-8 bg-white border rounded-2xl p-6"><div className="flex items-center gap-3"><Search className="text-blue-600"/><h2 className="font-bold">Wissenssuche</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full border rounded-xl px-4 py-3 mt-4" placeholder="z. B. RAG, lokales Modell, Datenschutz, Agent..." />{query&&<div className="mt-4 space-y-2">{search.map(x=><div key={x.id} className="p-3 bg-slate-50 rounded-xl"><b>{x.term}</b><span className="text-xs text-blue-600 ml-2">{x.category}</span><p className="text-sm text-slate-600">{x.definition}</p></div>)}</div>}</div>}
</div></div>};export default AIHub;
